services:
  conversor:
    build:
      context: ./todolist
      dockerfile: Dockerfile
    restart: always
    environment:
      MYSQL_URL: "jdbc:mysql://mysql-db:3306/todolist?allowPublicKeyRetrieval=true&useSSL=false"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: 123456
    expose:
      - "8080"
    ports:
      - "8080:8080"
    depends_on:
      - mysql-db
    networks:
      - app-network
  mysql-db:
    image: mysql:8.4.0
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: todolist
      MYSQL_USER: user
      MYSQL_PASSWORD: 123456
    ports:
      - "3306:3306"
    volumes:
      - database-mysql:/var/lib/mysql
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
volumes:
  database-mysql:
